<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Drivers\" />
    <Folder Include="TCP\" />
    <Folder Include="Serial\" />
    <Folder Include="Relay\" />
    <Folder Include="RFID\" />
  </ItemGroup>

</Project>
